let catalog=[],meta={};const $=s=>document.querySelector(s);const state={eq:[],new:[]};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function load(){try{const d=await fetch('data/affixes.json?v=2',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()});meta=d._meta||{};catalog=d.affixes.filter(a=>a.classes.includes('All')||a.classes.includes('Spiritborn')).sort((a,b)=>a.name.localeCompare(b.name));$('#dataBuild').textContent=(meta.d4lootbench_build||'Extracted data').replace('LootBenchDataExtract build ','');$('#catalogCount').textContent=catalog.length+' affixes';reset()}catch(e){$('#dataBuild').textContent='LOAD ERROR';$('#catalogCount').textContent='Unavailable';$('#summary').textContent='The catalog failed to load. Refresh the page.'}}
function options(selected){return '<option value="">Select an affix…</option>'+catalog.map(a=>'<option value="'+a.hash+'" '+(a.hash===selected?'selected':'')+'>'+esc(a.name)+'</option>').join('')}
function add(side,preset={}){if(state[side].length>=4)return;state[side].push({hash:preset.hash||'',value:preset.value||0,ga:!!preset.ga});render(side)}
function render(side){const host=$('#'+side+'Rows');host.innerHTML=state[side].map((x,i)=>{const a=catalog.find(y=>y.hash===x.hash);return '<div class="affixrow"><select class="affix-select" data-side="'+side+'" data-i="'+i+'">'+options(x.hash)+'</select><div class="meta">'+(a?'ID '+a.hash+' · '+esc(a.sno)+' · '+esc(a.classes.join(', ')):'Choose from canonical Spiritborn-compatible affixes')+'</div><div class="affixcontrols"><input type="number" step="any" min="0" data-value="'+side+':'+i+'" value="'+x.value+'"><label class="check"><input type="checkbox" data-ga="'+side+':'+i+'" '+(x.ga?'checked':'')+'> GA</label><button class="remove" type="button" data-remove="'+side+':'+i+'">Remove</button></div></div>'}).join('')}
document.addEventListener('change',e=>{if(e.target.matches('.affix-select')){let s=e.target.dataset.side,i=+e.target.dataset.i;state[s][i].hash=e.target.value;render(s)}if(e.target.dataset.value){let [s,i]=e.target.dataset.value.split(':');state[s][+i].value=Number(e.target.value)||0}if(e.target.dataset.ga){let [s,i]=e.target.dataset.ga.split(':');state[s][+i].ga=e.target.checked}});
document.addEventListener('click',e=>{if(e.target.matches('.add'))add(e.target.dataset.side);if(e.target.dataset.remove){let [s,i]=e.target.dataset.remove.split(':');state[s].splice(+i,1);render(s)}});
function snapshot(side){return state[side].filter(x=>x.hash).map(x=>({...x,a:catalog.find(y=>y.hash===x.hash)}))}
function evaluate(){const A=snapshot('eq'),B=snapshot('new');if(!A.length||!B.length){$('#verdict').textContent='WITHHELD';$('#summary').textContent='Both items need at least one recognized affix.';return}const am=new Map(A.map(x=>[x.hash,x])),bm=new Map(B.map(x=>[x.hash,x]));let gains=[],losses=[],improved=[],worse=[];for(const [id,b] of bm){const a=am.get(id);if(!a)gains.push(b);else if(b.value>a.value||(!a.ga&&b.ga))improved.push({a,b});else if(b.value<a.value||(a.ga&&!b.ga))worse.push({a,b})}for(const [id,a] of am)if(!bm.has(id))losses.push(a);let verdict='SIDEGRADE';if((gains.length||improved.length)&&!losses.length&&!worse.length)verdict='UPGRADE';else if(!(gains.length||improved.length)&&(losses.length||worse.length))verdict='DOWNGRADE';else if(!gains.length&&!losses.length&&!improved.length&&!worse.length)verdict='NO MEANINGFUL CHANGE';let eqQ=Number($('#eqQuality').value)||0,newQ=Number($('#newQuality').value)||0,eqT=$('#eqTemper').checked,newT=$('#newTemper').checked;if(verdict==='UPGRADE'&&(eqQ>newQ||(eqT&&!newT)))verdict='KEEP FOR DEVELOPMENT';$('#verdict').textContent=verdict;$('#summary').textContent='Catalog-valid comparison for Spiritborn. Build priority and slot legality are not scored yet, so v0.2 will not pretend this is a final build-aware recommendation.';$('#intrinsic').textContent=(gains.length+improved.length)+' gains/improvements · '+(losses.length+worse.length)+' losses/worsenings';$('#current').textContent='Equipped Quality '+eqQ+(eqT?' + temper':'')+' · Candidate Quality '+newQ+(newT?' + temper':'');let lines=[];gains.forEach(x=>lines.push('Gained: '+x.a.name));losses.forEach(x=>lines.push('Lost: '+x.a.name));improved.forEach(x=>lines.push('Improved: '+x.b.a.name+' '+x.a.value+' → '+x.b.value+(x.b.ga?' GA':'')));worse.forEach(x=>lines.push('Worsened: '+x.b.a.name+' '+x.a.value+' → '+x.b.value));$('#reasons').innerHTML=lines.map(x=>'<div class="reason"><span>'+esc(x)+'</span></div>').join('')||'<div class="reason">No intrinsic difference detected.</div>'}
$('#form').addEventListener('submit',e=>{e.preventDefault();evaluate()});$('#reset').addEventListener('click',reset);
function find(name){return catalog.find(a=>a.name===name)?.hash||''}function reset(){state.eq=[{hash:find('Attack Speed'),value:18},{hash:find('Dexterity'),value:80},{hash:find('Maximum Life'),value:500}];state.new=[{hash:find('Attack Speed'),value:22,ga:true},{hash:find('Dexterity'),value:86},{hash:find('Maximum Life'),value:450}];$('#eqQuality').value=25;$('#newQuality').value=0;$('#eqTemper').checked=true;$('#newTemper').checked=false;render('eq');render('new');$('#verdict').textContent='READY';$('#summary').textContent='Choose affixes from the current Spiritborn-compatible catalog, then compare.'}load();