let catalog=[],meta={},uniqueByInternal=new Map(),guaranteedByName=new Map();const $=s=>document.querySelector(s);const state={eq:[],new:[]};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function load(){try{const [d,u,ga]=await Promise.all([fetch('data/affixes.json?v=2',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}),fetch('data/uniques.json?v=1',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}),fetch('data/guaranteed-affixes.json?v=1',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()})]);guaranteedByName=new Map(Object.entries(ga.items||{}));uniqueByInternal=new Map((u.uniques||[]).filter(x=>x.internal).map(x=>[x.internal.toLowerCase(),x]));meta=d._meta||{};catalog=d.affixes.filter(a=>a.classes.includes('All')||a.classes.includes('Spiritborn')).sort((a,b)=>a.name.localeCompare(b.name));$('#dataBuild').textContent=(meta.d4lootbench_build||'Extracted data').replace('LootBenchDataExtract build ','');$('#catalogCount').textContent=catalog.length+' affixes';reset()}catch(e){$('#dataBuild').textContent='LOAD ERROR';$('#catalogCount').textContent='Unavailable';$('#summary').textContent='The catalog failed to load. Refresh the page.'}}
function options(selected){return '<option value="">Select an affix…</option>'+catalog.map(a=>'<option value="'+a.hash+'" '+(a.hash===selected?'selected':'')+'>'+esc(a.name)+'</option>').join('')}
function add(side,preset={}){if(state[side].length>=4)return;state[side].push({hash:preset.hash||'',value:preset.value||0,ga:!!preset.ga});render(side)}
function render(side){const host=$('#'+side+'Rows');host.innerHTML=state[side].map((x,i)=>{const a=catalog.find(y=>y.hash===x.hash);return '<div class="affixrow"><select class="affix-select" data-side="'+side+'" data-i="'+i+'">'+options(x.hash)+'</select><div class="meta">'+(a?'ID '+a.hash+' · '+esc(a.sno)+' · '+esc(a.classes.join(', ')):'Choose from canonical Spiritborn-compatible affixes')+'</div><div class="affixcontrols"><input type="number" step="any" min="0" data-value="'+side+':'+i+'" value="'+x.value+'"><label class="check"><input type="checkbox" data-ga="'+side+':'+i+'" '+(x.ga?'checked':'')+'> GA</label><button class="remove" type="button" data-remove="'+side+':'+i+'">Remove</button></div></div>'}).join('')}
document.addEventListener('change',e=>{if(e.target.matches('.affix-select')){let s=e.target.dataset.side,i=+e.target.dataset.i;state[s][i].hash=e.target.value;render(s)}if(e.target.dataset.value){let [s,i]=e.target.dataset.value.split(':');state[s][+i].value=Number(e.target.value)||0}if(e.target.dataset.ga){let [s,i]=e.target.dataset.ga.split(':');state[s][+i].ga=e.target.checked}});
document.addEventListener('click',e=>{if(e.target.matches('.add'))add(e.target.dataset.side);if(e.target.dataset.remove){let [s,i]=e.target.dataset.remove.split(':');state[s].splice(+i,1);render(s)}});
function snapshot(side){return state[side].filter(x=>x.hash).map(x=>({...x,a:catalog.find(y=>y.hash===x.hash)}))}
function evaluate(){const A=snapshot('eq'),B=snapshot('new');if(!A.length||!B.length){$('#verdict').textContent='WITHHELD';$('#summary').textContent='Both items need at least one recognized affix.';return}const am=new Map(A.map(x=>[x.hash,x])),bm=new Map(B.map(x=>[x.hash,x]));let gains=[],losses=[],improved=[],worse=[];for(const [id,b] of bm){const a=am.get(id);if(!a)gains.push(b);else if(b.value>a.value||(!a.ga&&b.ga))improved.push({a,b});else if(b.value<a.value||(a.ga&&!b.ga))worse.push({a,b})}for(const [id,a] of am)if(!bm.has(id))losses.push(a);let verdict='SIDEGRADE';if((gains.length||improved.length)&&!losses.length&&!worse.length)verdict='UPGRADE';else if(!(gains.length||improved.length)&&(losses.length||worse.length))verdict='DOWNGRADE';else if(!gains.length&&!losses.length&&!improved.length&&!worse.length)verdict='NO MEANINGFUL CHANGE';let eqQ=Number($('#eqQuality').value)||0,newQ=Number($('#newQuality').value)||0,eqT=$('#eqTemper').checked,newT=$('#newTemper').checked;if(verdict==='UPGRADE'&&(eqQ>newQ||(eqT&&!newT)))verdict='KEEP FOR DEVELOPMENT';$('#verdict').textContent=verdict;$('#summary').textContent='Catalog-valid comparison for Spiritborn. Build priority and slot legality are not scored yet, so v0.2 will not pretend this is a final build-aware recommendation.';$('#intrinsic').textContent=(gains.length+improved.length)+' gains/improvements · '+(losses.length+worse.length)+' losses/worsenings';$('#current').textContent='Equipped Quality '+eqQ+(eqT?' + temper':'')+' · Candidate Quality '+newQ+(newT?' + temper':'');let lines=[];gains.forEach(x=>lines.push('Gained: '+x.a.name));losses.forEach(x=>lines.push('Lost: '+x.a.name));improved.forEach(x=>lines.push('Improved: '+x.b.a.name+' '+x.a.value+' → '+x.b.value+(x.b.ga?' GA':'')));worse.forEach(x=>lines.push('Worsened: '+x.b.a.name+' '+x.a.value+' → '+x.b.value));$('#reasons').innerHTML=lines.map(x=>'<div class="reason"><span>'+esc(x)+'</span></div>').join('')||'<div class="reason">No intrinsic difference detected.</div>'}
$('#form').addEventListener('submit',e=>{e.preventDefault();evaluate()});$('#reset').addEventListener('click',reset);
function find(name){return catalog.find(a=>a.name===name)?.hash||''}function reset(){state.eq=[{hash:find('Attack Speed'),value:18},{hash:find('Dexterity'),value:80},{hash:find('Maximum Life'),value:500}];state.new=[{hash:find('Attack Speed'),value:22,ga:true},{hash:find('Dexterity'),value:86},{hash:find('Maximum Life'),value:450}];$('#eqQuality').value=25;$('#newQuality').value=0;$('#eqTemper').checked=true;$('#newTemper').checked=false;render('eq');render('new');$('#verdict').textContent='READY';$('#summary').textContent='Choose affixes from the current Spiritborn-compatible catalog, then compare.'}load();
/* v0.3 build/import layer */
let loadedBuild=null;
const MAXROLL_PROFILE='https://planners.maxroll.gg/profiles/load/d4/';
const MAXROLL_GAME='https://assets-ng.maxroll.gg/d4-tools/game/data.min.json';
function detectProvider(url){try{const h=new URL(url).hostname.toLowerCase();if(h.includes('maxroll.gg'))return'maxroll';if(h.includes('mobalytics.gg'))return'mobalytics';if(h.includes('d4builds.gg'))return'd4builds';return'unsupported'}catch{return null}}
function plannerId(url){try{const m=new URL(url).pathname.match(/\/d4\/planner\/([A-Za-z0-9]+)/);return m?.[1]||null}catch{return null}}
async function jsonFetch(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
function humanizeAffix(raw=''){let s=String(raw).replace(/^(S\d+|X\d+)_/,'').replace(/_Greater$/,'').replace(/^CoreStat_/,'').replace(/^DamageType_/,'').replace(/^Resistance_All$/,'All Resistance').replace(/^Life$/,'Maximum Life').replace(/^Armor$/,'Armor').replace(/^Movement_Speed$/,'Movement Speed').replace(/^AttackSpeed$/,'Attack Speed').replace(/^CooldownReductionCDR$/,'Cooldown Reduction').replace(/^Resource_Per_Second_Vigor$/,'Vigor per Second').replace(/^ResourceGain$/,'Resource Generation').replace(/^Damage_to_Vulnerable$/,'Vulnerable Damage').replace(/^Poison$/,'Poison Damage').replace(/_/g,' ');return s.replace(/\b\w/g,m=>m.toUpperCase())}
function resolveAffixName(sno){const local=catalog.find(a=>a.sno===sno||a.name===sno);return local?.name||humanizeAffix(sno)||sno}
function guaranteedMatch(label,a){const n=(a?.name||'').toLowerCase().replace(/[^a-z0-9]/g,'');const l=label.toLowerCase();if(l==='primary core stat')return /dexterity|strength|willpower|intelligence/.test(n);if(l==='weapon damage')return /weapondamage/.test(n);if(l==='critical strike chance')return /criticalstrikechance|critchance/.test(n);if(l==='maximum life')return /maximumlife|life/.test(n);if(l==='attack speed')return /attackspeed/.test(n);if(l==='armor')return n==='armor';if(l==='vigor per second')return /vigorpersecond|resourcepersecondvigor/.test(n);if(l.includes('skill ranks to core skills'))return /skillrank.*core|coreskills/.test(n);if(l.includes('skill ranks to basic skills'))return /skillrank.*basic|basicskills/.test(n);if(l.includes('skill ranks to all skills'))return /skillrank.*all|allskills/.test(n);if(l.includes('skill ranks to gorilla skills'))return /gorillaskills/.test(n);if(l.includes('skill ranks to potency skills'))return /potencyskills/.test(n);if(l.includes('skill ranks to touch of death'))return /touchofdeath/.test(n);if(l.includes('skill ranks to soar'))return /soar/.test(n);if(l.includes('multiplier'))return n.includes(l.replace('multiplier','').replace(/[^a-z0-9]/g,''));return n===l.replace(/[^a-z0-9]/g,'')}
function isInternalVariant(v){return /(^|[_-])(chk|check|test|debug)($|[_-])/i.test(v?.name||'')}
function itemType(raw=''){const s=raw.toLowerCase();for(const [k,v] of [['helm','Helm'],['chest','Chest Armor'],['gloves','Gloves'],['pants','Pants'],['boots','Boots'],['amulet','Amulet'],['ring','Ring'],['polearm','Weapon'],['staff','Weapon']])if(s.includes(k))return v;return null}
function normalizeMaxroll(profile,game,url,id){const B=GearLabBuildModel.empty(url,'maxroll');B.sourceBuildId=id;B.name=profile.name||'Maxroll build';B.class=profile.class||null;let data=typeof profile.data==='string'?JSON.parse(profile.data):profile.data;const nid=new Map(Object.entries(game.affixes||{}).map(([s,e])=>[e?.id,s]));const root=data?.data&&typeof data.data==='object'?data.data:data||{};const pool=root.items||{};const profiles=Array.isArray(root.profiles)?root.profiles:[];for(const [pi,p] of profiles.entries()){if(!p||typeof p!=='object')continue;const V=GearLabBuildModel.variant(p.name,pi);const equipped=p.items&&typeof p.items==='object'?p.items:{};for(const [slotNo,iid] of Object.entries(equipped)){const it=pool[String(iid)];if(!it?.id)continue;const type=itemType(it.id);if(!type){V.providerData['slot:'+slotNo]=it.id;continue}const key=type==='Ring'?(V.equipment['Ring 1']?'Ring 2':'Ring 1'):type;const S=GearLabBuildModel.slot();S.itemType=type;S.providerData.internalItemId=it.id;if(it.id.toLowerCase().includes('unique')){const canon=uniqueByInternal.get(it.id.toLowerCase());S.unique={name:canon?.name||humanizeAffix(it.id),providerId:it.id,canonicalId:canon?.hash||null};const ua=(it.explicits||[]).map(a=>{const sno=nid.get(a.nid)||null;return GearLabBuildModel.affix(sno,resolveAffixName(sno),!!a.greater)});/* Maxroll tells us the selected rolls, not which two are guaranteed. Preserve all selected affixes as build targets until the authoritative guaranteed-affix map resolves them. */const official=guaranteedByName.get(S.unique.name)||[];S.guaranteedAffixes=official.map(label=>{const hit=ua.find(a=>guaranteedMatch(label,a));const x=GearLabBuildModel.affix(hit?.id||null,hit?.name||label,!!hit?.desiredGA);x.providerData.officialLabel=label;x.providerData.source='Blizzard 3.1';return x});S.variableAffixes=ua.filter(a=>!official.some(label=>guaranteedMatch(label,a)));S.desiredAffixes=S.variableAffixes;S.providerData.guaranteedAffixResolution=official.length===2?'resolved':'unresolved';S.providerData.selectedUniqueAffixes=ua;S.tempers=(it.tempered||[]).map(a=>{const sno=nid.get(a.nid)||null;return GearLabBuildModel.affix(sno,resolveAffixName(sno),!!a.greater)})}else{for(const a of (it.explicits||[])){const sno=nid.get(a.nid)||null;S.desiredAffixes.push(GearLabBuildModel.affix(sno,resolveAffixName(sno),!!a.greater))}for(const a of (it.tempered||[])){const sno=nid.get(a.nid)||null;S.tempers.push(GearLabBuildModel.affix(sno,resolveAffixName(sno),!!a.greater))}}V.equipment[key]=S}V.providerData.rawProfile=p;if(!isInternalVariant(V))B.variants.push(V)}if(!B.variants.length){B.unresolved.push('No build variants found');throw new Error('Maxroll returned no build variants. Profile keys: '+Object.keys(data||{}).join(', ')+'; data keys: '+Object.keys(data?.data||{}).join(', '))}return B}
async function importMaxroll(url){let id=plannerId(url);if(!id)throw new Error('v0.3 currently needs a Maxroll planner URL. Guide-to-planner discovery is the next adapter step.');const [p,g]=await Promise.all([jsonFetch(MAXROLL_PROFILE+id),jsonFetch(MAXROLL_GAME)]);return normalizeMaxroll(p,g,url,id)}
function renderBuild(){if(!loadedBuild)return;$('#loadedBuild').classList.remove('hidden');$('#buildName').textContent=loadedBuild.name;$('#buildClass').textContent=loadedBuild.class||'Unknown class';$('#variant').innerHTML=loadedBuild.variants.map((v,i)=>'<option value="'+i+'">'+esc(v.name)+'</option>').join('');$('#buildMeta').innerHTML='<div><span>Provider</span><strong>'+esc(loadedBuild.provider)+'</strong></div><div><span>Variants</span><strong>'+loadedBuild.variants.length+'</strong></div><div><span>Source ID</span><strong>'+esc(loadedBuild.sourceBuildId||'—')+'</strong></div>';renderVariant();$('#filterBuildState').textContent=loadedBuild.name+' loaded. Filter generation will consume this same normalized model.'}
function selectedVariant(){return loadedBuild?.variants[Number($('#variant').value)||0]||null}
function buildSlotTarget(slot){const v=selectedVariant();if(!v)return null;if(slot==='Ring')return [v.equipment['Ring 1'],v.equipment['Ring 2']].filter(Boolean);return v.equipment[slot]||null}
function renderCompareTarget(){const host=$('#targetCard');if(!loadedBuild){host.classList.add('hidden');$('#slotHelp').textContent='Manual comparator remains available. Load a build to add build-aware targets.';return}const slot=$('#slot').value,t=buildSlotTarget(slot);host.classList.remove('hidden');if(!t||(Array.isArray(t)&&!t.length)){host.innerHTML='<p class="eyebrow">BUILD TARGET</p><h3>'+esc(slot)+'</h3><p class="muted">No target for this slot in '+esc(selectedVariant()?.name||'selected variant')+'.</p>';return}const targets=Array.isArray(t)?t:[t];host.innerHTML='<p class="eyebrow">BUILD TARGET · '+esc(selectedVariant().name)+'</p>'+targets.map((s,i)=>'<div class="targetslot"><h3>'+esc(Array.isArray(t)?'Ring '+(i+1):slot)+(s.unique?' · '+esc(s.unique.name):'')+'</h3><div class="chips">'+(s.unique?'<span class="chip">Required unique</span>'+s.guaranteedAffixes.map(a=>'<span class="chip">Guaranteed · '+esc(a.name||a.providerData?.officialLabel||'Unresolved')+'</span>').join('')+s.variableAffixes.map(a=>'<span class="chip '+(a.desiredGA?'ga':'')+'">'+esc(a.name||a.id||'Unresolved')+(a.desiredGA?' · Desired GA':'')+'</span>').join(''):s.desiredAffixes.map(a=>'<span class="chip '+(a.desiredGA?'ga':'')+'">'+esc(a.name||a.id||'Unresolved')+(a.desiredGA?' · Desired GA':'')+'</span>').join(''))+'</div></div>').join('');$('#slotHelp').textContent='Imported build targets are active. Manual item entry is still available.'}
function renderVariant(){if(!loadedBuild)return;const v=selectedVariant();if(!v){$('#slotTargets').innerHTML='<p class="muted">No variants were returned by the provider.</p>';$('#normalizedPreview').textContent=JSON.stringify(loadedBuild,null,2);return;}$('#slotTargets').innerHTML=Object.entries(v.equipment).map(([name,s])=>'<div class="targetslot"><h3>'+esc(name)+(s.unique?' · '+esc(s.unique.name):'')+'</h3><div class="chips">'+(s.unique?'<span class="chip">Required unique</span>'+s.guaranteedAffixes.map(a=>'<span class="chip">Guaranteed · '+esc(a.name||a.providerData?.officialLabel||'Unresolved')+'</span>').join('')+s.variableAffixes.map(a=>'<span class="chip '+(a.desiredGA?'ga':'')+'">'+esc(a.name||a.id||'Unresolved')+(a.desiredGA?' · GA':'')+'</span>').join(''):s.desiredAffixes.map(a=>'<span class="chip '+(a.desiredGA?'ga':'')+'">'+esc(a.name||a.id||'Unresolved')+(a.desiredGA?' · GA':'')+'</span>').join(''))+'</div></div>').join('')||'<p class="muted">No equipment targets resolved.</p>';$('#normalizedPreview').textContent=JSON.stringify({...loadedBuild,variants:[v]},null,2);renderCompareTarget();$('#filterBuildState').innerHTML='<strong>'+esc(loadedBuild.name)+' · '+esc(v.name)+'</strong><br>Normalized targets ready for transparent rule generation.'}
document.addEventListener('click',async e=>{if(e.target.matches('.tab')){document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#view-'+e.target.dataset.view).classList.add('active')}if(e.target.id==='importBuild'){const url=$('#buildUrl').value.trim(),p=detectProvider(url);$('#importStatus').textContent='Importing…';try{if(p!=='maxroll')throw new Error(p==='unsupported'?'That provider adapter is not implemented yet.':'Enter a valid build URL.');loadedBuild=await importMaxroll(url);renderBuild();$('#importStatus').textContent='Imported and normalized. Provider data remains separate from GearLab logic.'}catch(err){$('#importStatus').textContent='Import withheld: '+err.message}}});
$('#buildUrl').addEventListener('input',e=>{const p=detectProvider(e.target.value);$('#provider').textContent=p?({maxroll:'Maxroll',mobalytics:'Mobalytics (adapter reserved)',d4builds:'D4Builds (adapter reserved)',unsupported:'Unsupported provider'}[p]):'Waiting for URL'});
$('#variant').addEventListener('change',renderVariant);

$('#slot').addEventListener('change',renderCompareTarget);
